### ISSUE TITLE
Pull #872 might had introduced a regression in setting partition flags [master, kpmcore-3.2]

### ISSUE THREAD

**Issue by philmmanjaro** [calamares/calamares#880]
#### Submission type

  - [X] Bug report
  - [ ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

Calamares v3.1.11-2 (incl. kpmcore-3.2 branch) on Manjaro v17.1-rc2

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

Detailed logs can be found [here](https://hastebin.com/movowaxaso.vbs) and [here](https://hastebin.com/apocumetun.vbs).

Possible commits introducing the regression:

7ce52ec
55ed2ba
5c4286e
38688ba
139f5a9

#### What do you expect to have happen when Calamares installs?

Able to flag partitions as needed.

<img src="https://forum.manjaro.org/uploads/default/optimized/3X/2/6/26fc47598a92c842c7bffacbd6cd4461af7193f3_1_376x500.png">

<img src="https://forum.manjaro.org/uploads/default/original/3X/f/7/f7206876cc8d11990efdf22e3baa6fd7a7570f76.png">

#### Describe the issue you encountered

Calamares seems somehow not be able to flag partitions. A detailed description can be found [here](https://forum.manjaro.org/t/manjaro-v17-1-rc2-feedback-thread/36937/7).

#### Steps to reproduce the problem

Use the [latest development install media](https://manjaro.org/manjaro-preview-releases/) by Manjaro (v17.1-rc2) and try to flag partitions.

#### Include the installation.log (usually ~/Calamares/Calamares/Calamares.log, of the user Calamares runs as):

Detailed logs can be found [here](https://hastebin.com/movowaxaso.vbs) and [here](https://hastebin.com/apocumetun.vbs).

**Comment by eugen-manjaro** [comment]
I reported the above issue on the Manjaro forum.
I would like to add:
* If the EFI partition is flagged correctly by an external program (for example with KDE Partition Manager) the installation can proceed sucessfully.

I would like to add the [log](https://hastebin.com/ifoharakoz.vbs) with [calamares 3.1.11-3](https://forum.manjaro.org/t/manjaro-v17-1-rc2-feedback-thread/36937/19?u=eugen-b)

**Comment by eugen-manjaro** [comment]
The issue still persists with calamares 3.1.11-4 ([download](https://sourceforge.net/projects/manjarodev/files/users/philm/calamares/))
https://hastebin.com/ofayuzifac.vbs

**Comment by eugen-manjaro** [comment]
There is no issue with flags if you create a new partition. I deleted the old EFI partition in Manual partitioning of calamares 3.1.11-4 and created a new one, I set the boot and esp flags and got no error messages. The summary also states that the flags get set.
![screenshot_20171225_214650](https://user-images.githubusercontent.com/34839125/34342837-2dd3ea74-e9bd-11e7-8428-23be89d5507d.png)
Here is the log https://hastebin.com/sehamofahu.vbs

**Comment by abucodonosor** [comment]
OK but is _master_ + slots rename fix is broken or not ? 

Whatever you have master+ kpmcore-3.2 does not matter  , that branch is not released
nor really ready to use..

**Comment by stikonas** [comment]
master was already broken. kpmcore-3.2 was not necessary to see broken behaviour. Anyway, I noticed what is wrong @philmmanjaro commited the fix.

**Comment by philmmanjaro** [comment]
@abucodonosor: it matters to us in Manjaro. We use that latest code for **partition** module. Let see if it got fixed now with my latest patch. @eugen-manjaro: please test build **v3.1.11-5** you may find [here](https://sourceforge.net/projects/manjarodev/files/users/philm/calamares).

**Comment by eugen-manjaro** [comment]
@philmmanjaro still the same issue with v3.1.11-5, sadly. ([log](https://hastebin.com/ikisudujot.vbs))

**Comment by stikonas** [comment]
Yes, I can confirm that it still doesn't work with existing partitions. (New partitions are fixed though).

**Comment by philmmanjaro** [comment]
@eugen-manjaro: was it possible with **calamares 3.1.11-4**, which uses the [3.1.x-stable partition](https://github.com/calamares/calamares/tree/3.1.x-stable/src/modules/partition), to set flag on existing partitions as needed?

**Comment by stikonas** [comment]
It seems that it still doesn't work with commit before my

commit 139f5a9e86e7afcce1d9faf51b42655117051170
Author: Andrius Štikonas <andrius@stikonas.eu>
Date:   Wed Dec 6 14:47:54 2017 +0000

    Use KPMcore SetPartFlags operation.

So I don't think the other half of the issue is due to KPMcore.

**Comment by eugen-manjaro** [comment]
>  was it possible with calamares 3.1.11-4, which uses the 3.1.x-stable partition, to set flag on existing partitions as needed?
No, it wasn't possible for **existing** partitions, see [my post above](https://github.com/calamares/calamares/issues/880#issuecomment-353889483).

**Comment by philmmanjaro** [comment]
@eugen-manjaro: so the issue is with the upstream [3.1.x-stable partition module](https://github.com/calamares/calamares/tree/3.1.x-stable/src/modules/partition) also. We have fixed the regression which got introduced with https://github.com/calamares/calamares/commit/7ce52ecda72c18194ba3449588358a788b5710e6, however the fact that you can't flag existing partitions is still given.

So this is then a general issue with **CAL** as **kpmcore** code seems to be fine.

**Comment by eugen-manjaro** [comment]
I've just tested on another disk on my machine. It is an SSD with ID sdc (the previous test target was an HDD with ID sdb), it is used as btrfs raid0 device to sda, it has two *empty and unformatted* 256MiB partitions.
```
[manjaro@manjaro ~]$ lsblk -f
NAME   FSTYPE   LABEL                            UUID                                 MOUNTPOINT
loop0  iso9660  MJRO171R                         2017-12-23-14-53-46-00               /run/miso/bootmnt
loop1  squashfs                                                                       /run/miso/sfs/livefs
loop2  squashfs                                                                       /run/miso/sfs/mhwdfs
loop3  squashfs                                                                       /run/miso/sfs/desktopfs
loop4  squashfs                                                                       /run/miso/sfs/rootfs
sda                                                                                   
├─sda1 vfat                                      1B50-4EF2                            
├─sda2 ext2                                      302ae0b1-b913-471b-a1ab-3bb4575b4d00 
└─sda3 btrfs                                     ea59470a-443b-4dbd-90b9-b6e0e6b32876 
sdb                                                                                   
├─sdb1 btrfs    Linux                            cf269dfd-df9c-4939-a8ff-796a4ced6643 /mnt
├─sdb2 swap     swap                             e487a4eb-8a7f-4196-896e-10ca767c4269 
├─sdb3 vfat                                      3F55-6CC0                            
├─sdb4 ext4                                      f95bebe5-c388-4ebf-93d2-12087003cef4 
├─sdb5 xfs      DATA2                            3de85b28-17b3-4a39-bd5e-61b4e118d7fd 
└─sdb6 xfs      DataHDD                          bb0e217e-dc93-486c-93f8-c5d73dcf7c4d /run/miso/img_dev
sdc                                                                                   
├─sdc1                                                                                
├─sdc2                                                                                
└─sdc3 btrfs                                     ea59470a-443b-4dbd-90b9-b6e0e6b32876 
```
I now tried to mount /dev/sdc1 as /boot/efi and formatted it FAR32 with flags boot and esp. I mounted sdc3 as /. I got **no** error!

So, it seems to happen only on a pre-formatted partition with a flag. It looks like even if I set no flag in KDE Partition Manager the flas `msftdata` gets set by default. Which makes flag setting in Calamares fail, hypothetically.

**Comment by philmmanjaro** [comment]
OK, @eugen-manjaro: can you check [Manjaro v17.0.6](https://sourceforge.net/projects/manjarolinux/files/release/17.0.6/kde/), which ships with **kpmcore v3.2** and an older **CAL**. I assume it might be similar. [Manjaro v17.0.5](https://sourceforge.net/projects/manjarolinux/files/release/17.0.5/kde/) ships with **kpmcore v3.1.2**. I simply wonder if this "issue" exists longer as its current detection ...

**Comment by philmmanjaro** [comment]
@eugen-manjaro: maybe you add a step by step guide on how you test this. I assume you want to re-use a partition, which has some flags and adding new flags failed somehow, at least for the ESP formatted as **fat32**.

**Comment by stikonas** [comment]
Just to clarify, msftdata is really just MBR/GPT partititon type. KPM has to set appropriate partition type, else Windows wouldn't see those FAT/NTFS partitions.

**Comment by eugen-manjaro** [comment]
A step by step description how I test:
* I have the following `parted -l` output for my test HDD which makes flagging fail:
```
Model: ATA ST500LM012 HN-M5 (scsi)
Disk /dev/sdb: 500GB
Sector size (logical/physical): 512B/4096B
Partition Table: gpt
Disk Flags: 

Number  Start   End    Size    File system     Name      Flags
 3      1049kB  269MB  268MB   fat32                     msftdata
 1      160GB   241GB  81.9GB  btrfs           btrfsHDD
 4      241GB   287GB  45.1GB  ext4
 6      287GB   391GB  105GB   xfs             DataHDD
 5      391GB   491GB  99.6GB  xfs
 2      491GB   500GB  9106MB  linux-swap(v1)  swap
```
And on this SSD flagging works when I format the unformatted partition sdc1
```
Model: ATA SAMSUNG MZHPU128 (scsi)
Disk /dev/sdc: 128GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End    Size   File system  Name  Flags
 1      1049kB  269MB  268MB
 2      269MB   538MB  268MB
 3      538MB   128GB  127GB  btrfs
```
* boot a Manjaro live system (I boot from the ISO with a custom Grub entry, a live USB or a VM should produce the same result)
* In a terminal emulator run `sudo -E calamares -d`
* In "Partitions" screen (4th screen) select  the drive to install to and "Manual partitioning"
* In the next screen select the "Storage device", mount the root partition.
  * Mount the EFI partition on /boot/efi, set the flags `boot` and `esp` remove the flag `msft-data`. Either select "Keep" or "Format", doesn't matter both fails.
![2017-12-25-233746_1920x1080_scrot](https://user-images.githubusercontent.com/34839125/34343418-b54d48bc-e9c5-11e7-8e57-6693a5df1922.png)

* The next screen presents you with an error message.
![2017-12-25-234341_500x241_scrot](https://user-images.githubusercontent.com/34839125/34343420-c092d174-e9c5-11e7-81f1-8408b489e413.png)

**Comment by eugen-manjaro** [comment]
I verified now the error with Manjaro 17.0.5 LXDE edition, calamares **3.1.4-9**.
However, going back from the "Users" screen and then
* deleting the EFI partition and creating a new one with flags `boot` and `esp` and clicking Next succeeds without errors.

**Comment by philmmanjaro** [comment]
OK, so I did the following so far.

**KaOS v2017.11**

* got the latest ISO from KaOS
* booted with EFI mode
* started the installer **CAL v3.1.7-git**
* used manual partitioning and reselect the 300 mb fat32 partition (already flagged with **boot** and **esp**.)
* selected the remaining second partition as root and only formatted that one
* installation and boot-up went fine

**Manjaro KDE v17.1-rc2**

* started the ISO
* selected the Calamares installer and moved to manual partitioning
* selected again the first partition, which is still 300 MB as fat32 formatted and has flags **esp** and **boot**. This time I selected format
* reused the root partition as given and selected format ext4
* installation and boot-up went fine

So again, @eugen-manjaro: what is the exact issue here. Did you uncheck and recheck then **boot** and **esp** or what was done on your end. On my end I didn't had to re-flag the partition, as it was flagged already.

```
[manjaro@manjaro ~]$ sudo parted -l
Model: ATA VBOX HARDDISK (scsi)
Disk /dev/sda: 13.2GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name  Flags
 1      2098kB  317MB   315MB   fat32              boot, esp
 2      317MB   13.2GB  12.9GB  ext4
```

**Comment by eugen-manjaro** [comment]
@philmmanjaro Indeed, there are no issues when already the correct flags are set - boot and esp.
You only get an error message if you had the wrong flags for the ESP.
However, I mean to just have found out that the error message might be just a cosmetic one, because if I ignore it I can install perfectly fine - te summary screen detects that the flags are set correctly:
![2017-12-26-000622_1080x741_scrot](https://user-images.githubusercontent.com/34839125/34343517-09d9f86a-e9d2-11e7-8767-c84302b31e22.png)
This is calamares 3.1.4-9.

**Comment by philmmanjaro** [comment]
@eugen-manjaro: what do you mean exactly with the wrong flags for the ESP? This `msft-data` flag or what? How exactly do you set the flags?

**Comment by eugen-manjaro** [comment]
To get `msftdata` flag I format the partition but set no flags in GParted, gnome-disks or KDE Partition Manager.

**Comment by eugen-manjaro** [comment]
The issue is that you get an error message in screen 5 "Users" if you started Calamares with a FAT partition without an esp flag. You set the esp flag in the popup window "Edit Existing Partition", but you get the error message nevertheless. The should be some check on the OK button in that window to avoid users getting confused by the error message. The flags selected should get passed to a variable which gets checked in the next screen "Users".

**Comment by eugen-manjaro** [comment]
Verified the same behaviour on calamares 3.1.7-3 (Manjaro Cinnamon 17.0.6 rc2).
Last one I *want* to verify is 3.1.11-4.

**Comment by philmmanjaro** [comment]
Ok, what I did:

* I reformatted the 300 MiB fat32 in partitionmanager and removed the flags before. I only got the `msft-data` flag
* I marked it as `/boot/efi` without setting the flags `boot` and `esp`
* root partition got formatted as `ext4` and set as `/`
* I got followed warning in **user** window (the message itself is part of **partition** module): An EFI system partition is necessary to start Manjaro. A partition was configured with mount point /boot/efi but its esp flag is not set. To set the flag, go back and edit the partition. You can continue without setting the flag but your system may fail to start.
* Went back to set `boot` and `esp` and continued. The message got shown again. I ignored it.
* Summary showed: Flag partition `/dev/sda1` as `msft-data, boot, esp`
* Installation went fine and booted: [install log](https://gist.githubusercontent.com/philmmanjaro/4daa0bea4ed682d013b3bd3912ee7fcb/raw/e1e6ffb2c5446b1c78c4bd80a3122444cce8496e/cal-3.1.11-5-flag.txt)

```
Model: ATA VBOX HARDDISK (scsi)
Disk /dev/sda: 13,2GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name  Flags
 1      2098kB  317MB   315MB   fat32              boot, esp
 2      317MB   13,2GB  12,9GB  ext4
```

So with current checks we check the following:

* `if ( !esp )` No EFI system partition configured
* `if ( esp && !esp->activeFlags().testFlag( PartitionTable::FlagEsp ) )` EFI system partition flag not set

However, we never test if the right partition is marked to be get flagged. The regression not able to do so, introduced via https://github.com/calamares/calamares/commit/7ce52ecda72c18194ba3449588358a788b5710e6, got fixed with https://github.com/calamares/calamares/commit/8f32aad3fa03f93728ccc79ba65564e22e48bc99. So now we have to find an additional way also to check if the ESP partition will get flagged correctly in a later step.

**Comment by philmmanjaro** [comment]
I searched the code and found this:

* Current **EFI** check got introduced with **v3.1.-beta2**: https://github.com/calamares/calamares/commit/0c7b7ed0892958851a28e4d532a06d541152343b
* Check then got moved to `onLeave()` with **v3.1-beta2**: https://github.com/calamares/calamares/commit/fb5b48528b2debb13969ee89058d6dadf435f6e6

So it was never modified since creation, to check also things happen to flags in a later step.

**Comment by eugen-manjaro** [comment]
I verified the behaviour with CAL **3.1.11-4**.
Format ESP in GParted to fat32, however here the flags get preserved! I removed them (`boot` and `esp`) and `msftdata` flag got set automatically.
Then I set the `boot` and `esp` flags and remove `msftdata` flag in Calamares.
Got the error message in the next window, ignored it and the Summary showed that the flags get set, the installation worked then.

**Comment by philmmanjaro** [comment]
@eugen-manjaro: yes, since beginning of the check we never checked for flags being set in a future step. Only for flags already set. We have to enhance the check to avoid unneeded warnings.

**Comment by philmmanjaro** [comment]
@stikonas: any idea on how to extend the check for flags also on those flags not set yet, but to be set in a later step?

**Comment by philmmanjaro** [comment]
Since the issue is solved by now and the warning display loop exists since **v3.1-beta2** we will close this bug and continue the matter within https://github.com/calamares/calamares/issues/884.
